C:\Python34\python.exe C:/Users/Ninad/PycharmProjects/plugable_arch/consumer.py
2014-06-20 00:41:16.802190 [DEBUG] Searching 'C:\Users\Ninad\PycharmProjects\plugable_arch' for addons...
2014-06-20 00:41:16.802190 [DEBUG]   - Addon file 'C:\Users\Ninad\PycharmProjects\plugable_arch\Default\CommandLineAddon.py' found...
2014-06-20 00:41:16.832191 [DEBUG]    - Loaded addon: 'CommandLineAddon'
2014-06-20 00:41:16.832191 [DEBUG]   - Addon file 'C:\Users\Ninad\PycharmProjects\plugable_arch\Default\FileIOAddon.py' found...
2014-06-20 00:41:16.844192 [DEBUG]    - Loaded addon: 'FileIOAddon'
2014-06-20 00:41:16.844192 [DEBUG]   - Addon file 'C:\Users\Ninad\PycharmProjects\plugable_arch\Default\PingAddon.py' found...
2014-06-20 00:41:16.851192 [DEBUG]    - Loaded addon: 'PingAddon'
2014-06-20 00:41:16.851192 [DEBUG] Validating addon: 'CommandLineAddon'
2014-06-20 00:41:16.851192 [DEBUG] Passed...
2014-06-20 00:41:16.851192 [DEBUG] Validating addon: 'FileIOAddon'
2014-06-20 00:41:16.851192 [DEBUG] Passed...
2014-06-20 00:41:16.851192 [DEBUG] Validating addon: 'PingAddon'
2014-06-20 00:41:16.852193 [DEBUG] Passed...
2014-06-20 00:41:16.852193 [DEBUG] Total '3' addon(s) loaded
Initializing CommandLineAddon module

        Name               : CommandLineAddon
        Description        : Command line addon for client, this is supposed to provide CLI validation
        Version            : 1.0.5
        Type               : 1
        Type Description   : Addon
        Execution Sequence : ['start', 'execute']
        Stop Sequence      : ['stop']
        UUID               : EEA8B330-A999-4D9F-89AB-D341330B619F

        Author             : juguar-team
        Help Link          : http://www.google.com/easydep/addon/CommandLineAddon.html

Starting activity in module CommandLineAddonfrom dir C:\Users\Ninad\PycharmProjects\plugable_arch
Executing activity in module CommandLineAddon
 Volume in drive C has no label.
 Volume Serial Number is 3AA2-5E06

 Directory of C:\Users\Ninad\PycharmProjects\plugable_arch

06/20/2014  12:41 AM    <DIR>          .
06/20/2014  12:41 AM    <DIR>          ..
06/20/2014  12:40 AM    <DIR>          .idea
06/20/2014  12:41 AM               206 addon-loader.info
06/20/2014  12:23 AM            12,006 addon.py
06/20/2014  12:39 AM             2,878 consumer.py
06/15/2014  03:50 PM    <DIR>          Default
06/12/2014  12:15 AM             1,747 Helpers.py
06/13/2014  12:05 AM    <DIR>          Hook
06/16/2014  10:04 AM             4,257 IAddonInfo.py
06/14/2014  10:39 PM               360 ILog.py
06/12/2014  11:34 PM             2,886 loader.py
06/20/2014  12:41 AM    <DIR>          __pycache__
               7 File(s)         24,340 bytes
               6 Dir(s)   1,388,834,816 bytes free
Stopping activity in module CommandLineAddon
Starting activity in module CommandLineAddonfrom dir C:\Users\Ninad\PycharmProjects\plugable_arch
Executing activity in module CommandLineAddon
 Volume in drive C has no label.
 Volume Serial Number is 3AA2-5E06

 Directory of C:\Users\Ninad\PycharmProjects\plugable_arch

06/20/2014  12:41 AM    <DIR>          .
06/20/2014  12:41 AM    <DIR>          ..
06/20/2014  12:40 AM    <DIR>          .idea
06/20/2014  12:41 AM               206 addon-loader.info
06/20/2014  12:23 AM            12,006 addon.py
06/20/2014  12:39 AM             2,878 consumer.py
06/15/2014  03:50 PM    <DIR>          Default
06/12/2014  12:15 AM             1,747 Helpers.py
06/13/2014  12:05 AM    <DIR>          Hook
06/16/2014  10:04 AM             4,257 IAddonInfo.py
06/14/2014  10:39 PM               360 ILog.py
06/12/2014  11:34 PM             2,886 loader.py
06/20/2014  12:41 AM    <DIR>          __pycache__
               7 File(s)         24,340 bytes
               6 Dir(s)   1,388,826,624 bytes free
Stopping activity in module CommandLineAddon
Initializing FileIOAddon module

        Name               : FileIOAddon
        Description        : File IO related operations will be done with this addon
        Version            : 1.0.5
        Type               : 0
        Type Description   : CoreAddon
        Execution Sequence : ['start', 'execute']
        Stop Sequence      : ['stop']
        UUID               : 5b2dd0d5-2bbd-40a9-8250-c21167dbb822

        Author             : juguar-team
        Help Link          : http://www.google.com/easydep/addon/FileIOAddon.html

Executing activity in module FileIOAddon
Starting activity in module FileIOAddon
Stopping activity in module FileIOAddon
Initializing PingAddon module

        Name               : PingAddon
        Description        : Run in finitie loop and throw exception...just for fun
        Version            : 1.0.0.1
        Type               : 2
        Type Description   : AddonOverload
        Execution Sequence : ['start', 'pause', 'execute']
        Stop Sequence      : ['stop']
        UUID               : 9d28d505-27ac-435e-8e8c-0f7ddfaa8236

        Author             : juguar-team
        Help Link          : http://www.google.com/easydep/addon/PingAddon.html

starting loop till 10....
Pinging Server: Attempt 0
Pinging Server: Attempt 1.
Pinging Server: Attempt 2..
Pinging Server: Attempt 3...
Pinging Server: Attempt 4....
Pinging Server: Attempt 5.....
Pinging Server: Attempt 6......
Pinging Server: Attempt 7.......
Pinging Server: Attempt 8........
Pinging Server: Attempt 9.........
just a pause b/w the setup & actual execution but i will throw exception..
Pinging Server: Attempt 0
Pinging Server: Attempt 1.
Pinging Server: Attempt 2..
Pinging Server: Attempt 3...
Pinging Server: Attempt 4....
Pinging Server: Attempt 5.....
Addon thrown exception, better catch it ...This can not be more than 4!!!!!
Stopping activity in module PingAddon
Traceback (most recent call last):
  File "C:/Users/Ninad/PycharmProjects/plugable_arch/consumer.py", line 76, in <module>
    run_mgr.execute_with_config(pingadd)
  File "C:\Users\Ninad\PycharmProjects\plugable_arch\addon.py", line 245, in execute_with_config
    self.__run(addon, addon.get_start_seq(), addon.get_stop_seq())
  File "C:\Users\Ninad\PycharmProjects\plugable_arch\addon.py", line 260, in __run
    e_func()
  File "C:\Users\Ninad\PycharmProjects\plugable_arch\Default\PingAddon.py", line 29, in pause
    raise ArithmeticError("This can not be more than 4!!!!!")
ArithmeticError: This can not be more than 4!!!!!

Process finished with exit code 1
